var TEXT_WIN  = "YOU WIN";
var TEXT_LOSE = "YOU LOSE";
var TEXT_SCORE     = "SCORE: %s";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_YOUR_FLEET = "YOUR FLEET";
var TEXT_ENEMY_FLEET = "ENEMY FLEET";
var TEXT_STRATEGY_PANEL = "STRATEGY PANEL";
var TEXT_GAME_MODE = "GAME MODE";
var TEXT_CLASSIC = "CLASSIC";
var TEXT_ADVANCED = "ADVANCED";
var TEXT_COST = "COST: %s";
var TEXT_SUNK = "SUNK";
var TEXT_HELP = "HELP";
var TEXT_HELP_CLASSIC = "CLICK ON A CELL AND GUESS THE POSITION OF YOUR ENEMY'S SHIP TO DESTROY THEM";
var TEXT_HELP_ADVANCED = "COLLECT POINTS TO BUY THE POWER-UPS";
var TEXT_HELP_AIRSTRIKE = "HITS RANDOM CELLS OT ONCE";
var TEXT_HELP_RADAR = "REVEALS THE POSITION OF AN OPPONENT'S SHIP";
var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_DEVELOPED = "DEVELOPED BY";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";